version: '3.3'

services: 

  dwh: 
    image: postgres:alpine 
    container_name: ${STACK_NAME}_postgres-db
    restart: ${RESTART_POLICY} 
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: 
    - "5432:5432"
    volumes:
    - ./my-postgres.conf:/etc/postgresql/postgresql.conf