version: '3.3'

services: 

  dwh: 
    image: 'postgres:latest' 
    container_name: postgres-dwh
    restart: always 
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dwh
    ports: 
    - "5432:5432"
    volumes:
    - ./my-postgres.conf:/etc/postgresql/postgresql.conf